name: explorer
description: "An app to gather all sensor data from the smartphone."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0 # Correct indentation
  cupertino_icons: ^1.0.2
  sensors_plus: ^4.0.2
  location: ^5.0.3
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.5
  camerawesome: ^2.0.1
  camera: ^0.10.5+9
  open_file: ^3.3.2
  flutter_background_service: ^5.0.5
  permission_handler: ^11.3.0
  image_gallery_saver: ^2.0.3
  gallery_saver: ^2.3.2
  csv: ^6.0.0
  file_picker: ^6.1.1
  awesome_dialog: ^3.2.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.68.0
  get: ^4.6.6
  share_plus: ^9.0.0
  circular_countdown_timer: ^0.2.3
  geolocator: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/upscalar.png

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab-VariableFont_wght.ttf